import { Router } from 'express';
import rateLimit from 'express-rate-limit';
import { createAuthController } from '../controllers/authController.js';
import { createCatalogController } from '../controllers/catalogController.js';
import { createCouponController } from '../controllers/couponController.js';
import { createOrderController } from '../controllers/orderController.js';
import { createProductController } from '../controllers/productController.js';
import { createProductImportController } from '../controllers/productImportController.js';
import { createSiteSettingController } from '../controllers/siteSettingController.js';
import { requireAdmin } from '../middleware/auth.js';
import { uploadProductCsv } from '../middleware/upload.js';
import asyncHandler from '../utils/asyncHandler.js';

export default function createAdminRoutes({ authService, orderService, catalogService, productService, productImportService, siteSettingService, couponService }) {
  const router = Router();
  const auth = createAuthController(authService);
  const orders = createOrderController(orderService);
  const catalog = createCatalogController(catalogService);
  const products = createProductController(productService);
  const coupons = createCouponController(couponService);
  const productImports = createProductImportController(productImportService);
  const settings = createSiteSettingController(siteSettingService);
  const limiter = rateLimit({ windowMs: 15 * 60 * 1000, limit: 15, standardHeaders: 'draft-8', legacyHeaders: false });
  router.post('/login', limiter, asyncHandler(auth.adminLogin));
  router.post('/logout', requireAdmin, asyncHandler(auth.adminLogout));
  router.get('/brands', requireAdmin, asyncHandler(catalog.brands));
  router.post('/brands', requireAdmin, asyncHandler(catalog.createBrand));
  router.put('/brands/:id', requireAdmin, asyncHandler(catalog.updateBrand));
  router.delete('/brands/:id', requireAdmin, asyncHandler(catalog.deleteBrand));
  router.get('/categories', requireAdmin, asyncHandler(catalog.categories));
  router.post('/categories', requireAdmin, asyncHandler(catalog.createCategory));
  router.put('/categories/:id', requireAdmin, asyncHandler(catalog.updateCategory));
  router.delete('/categories/:id', requireAdmin, asyncHandler(catalog.deleteCategory));
  router.get('/catalog-options', requireAdmin, asyncHandler(catalog.options));
  router.post('/catalog-options', requireAdmin, asyncHandler(catalog.createOption));
  router.put('/catalog-options/:id', requireAdmin, asyncHandler(catalog.updateOption));
  router.get('/coupons', requireAdmin, asyncHandler(coupons.list));
  router.post('/coupons', requireAdmin, asyncHandler(coupons.create));
  router.put('/coupons/:id', requireAdmin, asyncHandler(coupons.update));
  router.delete('/coupons/:id', requireAdmin, asyncHandler(coupons.archive));
  router.get('/products/import/template', requireAdmin, asyncHandler(productImports.template));
  router.get('/products/import/history', requireAdmin, asyncHandler(productImports.history));
  router.get('/products/import/history/:id/failures.csv', requireAdmin, asyncHandler(productImports.failedReport));
  router.post('/products/import', requireAdmin, uploadProductCsv, asyncHandler(productImports.process));
  router.put('/size-guide', requireAdmin, asyncHandler(settings.updateSizeGuide));
  router.put('/payment-settings', requireAdmin, asyncHandler(settings.updatePaymentSettings));
  router.get('/homepage-media', requireAdmin, asyncHandler(settings.adminHomepageMedia));
  router.put('/homepage-media', requireAdmin, asyncHandler(settings.updateHomepageMedia));
  router.get('/products', requireAdmin, asyncHandler(products.adminList));
  router.get('/products/:id', requireAdmin, asyncHandler(products.adminGet));
  router.get('/orders', requireAdmin, asyncHandler(orders.adminList));
  router.get('/customers/search', requireAdmin, asyncHandler(orders.adminCustomers));
  router.post('/orders/quote', requireAdmin, asyncHandler(orders.adminQuote));
  router.post('/orders', requireAdmin, asyncHandler(orders.adminCreate));
  router.put('/orders/:id/status', requireAdmin, asyncHandler(orders.updateStatus));
  return router;
}
